# Generated by Django 4.1.4 on 2023-02-27 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shortner", "0002_rename_urls_url"),
    ]

    operations = [
        migrations.RenameField(model_name="url", old_name="links", new_name="link",),
    ]
